config/routes.rb
Rails.application.routes.draw do
  #setting index page
  get 'zipcodes/index'
  get 'zipcodes/list'
  #displaying the resource to use
  resources :zipcodes do
    resources :list
  end
  #root file
  root 'zipcodes#index'
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/zipcodes_controller.rb
class ZipcodesController < ApplicationController

  def new
    puts 'test'
  end

  def show
    @zipcodes = Zipcode.find(params[:id])
  end

  def create
    @zipcodes = Zipcode.new(zipcode_params)

    @zipcodes.save
    redirect_to @zipcodes
  end

  def list
    @zipcodes = Zipcode.all
  end

  private
  def zipcode_params
    params.require(:zipcodes).permit(:zipcode, :place)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/zipcodes_helper.rb
module ZipcodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restruby</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.indigo-pink.min.css">
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/welcome/index.html.erb
<%= form_for :zipcodes do |f| %>
  <p>
    <%= f.label :zipcodes %><br>
    <%= f.text_field :zipcodes %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/zipcodes/index.html.erb
<h1>Enter a Zipcode</h1>

<%= form_for :zipcodes, url: zipcodes_path do |f| %>
  <p>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <input class="mdl-textfield__input" name='zipcodes[zipcode]' type="text" pattern="-?[0-9]*(\.[0-9]+)?" id="zipcodes_zipcode" onchange='wayTooLate()' onfocusout='wayTooLate()'>
    <label class="mdl-textfield__label" for="zipcodes_zipcode">Enter a Zipcode</label>
    <span class="mdl-textfield__error">Input is not a number!</span>

  </div>
<input type='button' class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" id='test' value='Check' onclick="wayTooLate()" />

  <p>
  <input type="hidden" value='' name="zipcodes[place]" id="zipcodes_place" />
  </p>
  <span id='queryStatus'>City Name</span>

  <p>
    </p>
<% end %>

<p>
<%= link_to 'Show Zipcodes', 'zipcodes/list' %>
</p>




<script>
function wayTooLate(){
  var client = new XMLHttpRequest();
  var placeData = document.getElementById('zipcodes_place').value
    var zipData = document.getElementById('zipcodes_zipcode').value;
  client.open("GET", "http://api.zippopotam.us/us/"+zipData, true);
  client.onreadystatechange = function() {
    if(client.readyState == 4) {
      if(client.status === 200) {
        var tooLate = client.responseText;
        var placeName = JSON.parse(tooLate).places[0]['place name'];
        document.getElementById('zipcodes_place').value = placeName;
        document.getElementById('test').value = 'Submit Zipcode?';
        document.getElementById('test').name = 'commit';
        document.getElementById('test').type = 'submit';
        document.getElementById('queryStatus').innerHTML = 'The city for this zipcode is '+placeName;
      } else {
        document.getElementById('queryStatus').innerHTML = 'There is no zipcode for this.'
      }
    }
  };
  client.send()
}
</script>

<script type="text/javascript">
function stopRKey(evt) {
  var evt = (evt) ? evt : ((event) ? event : null);
  var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null);
  if ((evt.keyCode == 13) && (node.type=="text"))  {return false;}
}

document.onkeypress = stopRKey;
</script>

app/views/zipcodes/list.html.erb
<h2>Zipcodes Entered</h2>
<a href='/'>Enter a new zipcode</a>
<table>
  <tr>
    <th>zipcode</th>
    <th>place</th>
  </tr>

  <% @zipcodes.each do |zipcodes| %>
    <tr>
      <td><%= zipcodes.zipcode %></td>
      <td><%= zipcodes.place %></td>
    </tr>
  <% end %>
</table>

app/views/zipcodes/new.html.erb
<h1>Enter a Zipcode</h1>
<%= form_for :zipcodes, url: zipcodes_path do |f| %>
  <p>
  <%= f.label :zipcode %><br/>
  <%= f.text_field :zipcode %>
  </p>

  <p>
  <%= f.label :place %><br/>
  <%= f.text_field :place %>
  </p>

  <p>
  <%= f.submit %>
  </p>
  <% end %>

  <p>
  <%= link_to 'Show Zipcodes', 'zipcodes/list' %>
  </p>

app/views/zipcodes/show.html.erb
<p>
  <strong>zipcode</strong>
  <%= @zipcodes.zipcode %>
</p>

<p>
  <strong>location:</strong>
  <%= @zipcodes.place %>
</p>

<%= link_to 'Show Zipcodes', '/zipcodes/list' %>